name: admin_panell
description: تطبيق لوحة إدارة النظام.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_models:
    path: ../shared_modules/shared_models

  shared_services:
    path: ../shared_modules/shared_services

  shared_widgets:
    path: ../shared_modules/shared_widgets

  flutter_secure_storage: ^9.2.2

  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
