// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7DAaH1T4F5TT_BoP-Ygo6mW7SIBgVTk',
    appId: '1:221364713495:web:e81f1184d3ed01421a0452',
    messagingSenderId: '221364713495',
    projectId: 'rrrrrr-3df72',
    authDomain: 'rrrrrr-3df72.firebaseapp.com',
    storageBucket: 'rrrrrr-3df72.firebasestorage.app',
    measurementId: 'G-7KK8BHDQE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pl7qUxsdagsDoci6VbMQOKeIR6SS8Vg',
    appId: '1:221364713495:android:580418385d86943a1a0452',
    messagingSenderId: '221364713495',
    projectId: 'rrrrrr-3df72',
    storageBucket: 'rrrrrr-3df72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrao1rk1cf4B3-n-J1NU1KXngcy6DX6b4',
    appId: '1:221364713495:ios:f7f0fca07e419e3c1a0452',
    messagingSenderId: '221364713495',
    projectId: 'rrrrrr-3df72',
    storageBucket: 'rrrrrr-3df72.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrao1rk1cf4B3-n-J1NU1KXngcy6DX6b4',
    appId: '1:221364713495:ios:f7f0fca07e419e3c1a0452',
    messagingSenderId: '221364713495',
    projectId: 'rrrrrr-3df72',
    storageBucket: 'rrrrrr-3df72.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH7DAaH1T4F5TT_BoP-Ygo6mW7SIBgVTk',
    appId: '1:221364713495:web:f56126accee883531a0452',
    messagingSenderId: '221364713495',
    projectId: 'rrrrrr-3df72',
    authDomain: 'rrrrrr-3df72.firebaseapp.com',
    storageBucket: 'rrrrrr-3df72.firebasestorage.app',
    measurementId: 'G-L164Y6XWHS',
  );
}
